In [5]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report

In [6]:
df = pd.read_csv("./Data/adult.csv")

df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [7]:
# Convert target label (income) into numeric class
df['Income_Class'] = (df['income'] == '>50K').astype(int)

df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,Income_Class
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K,0
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K,0
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K,1
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K,1
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K,0

In [8]:
# Encode Gender column
df['gender'] = df['gender'].map({'Male':1, 'Female':0})

In [9]:
# Select Features
X = df[['age', 'educational-num', 'hours-per-week', 'gender']]
# Target
y = df['Income_Class']

In [10]:
# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
# Create Model
model = GaussianNB()

# Train Model
model.fit(X_train, y_train)

In [12]:
# Predictions
y_pred = model.predict(X_test)

# Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
# Sample Prediction
sample = [[35, 13, 45, 1]]  # age, education-num, hours-per-week, gender

prediction = model.predict(sample)

if prediction[0] == 1:
    print("Income: >50K")
else:
    print("Income: <=50K")

Accuracy: 0.8064284983109837

Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.91      0.88      7479
           1       0.61      0.47      0.53      2290

    accuracy                           0.81      9769
   macro avg       0.73      0.69      0.70      9769
weighted avg       0.79      0.81      0.80      9769

Income: >50K

C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

#### The Gaussian Naive Bayes model was used to classify whether a person's income is greater than 50K or less than or equal to 50K based on features such as age, education level, working hours per week, and gender. The dataset was split into training and testing sets, and the model was trained on the training data. The accuracy score and classification report were used to evaluate the model’s performance. The model can also predict the income class for new input data based on the learned patterns.